// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace NumericSequenceCalculatorUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// NumberEntered - Use 'NumberEnteredParams' to pass parameters into this method.
        /// </summary>
        public void NumberEntered()
        {
            #region Variable Declarations
            HtmlEdit uINumberEdit = this.UIHomePageNumericSequeWindow.UIHomePageNumericSequeDocument.UINumberEdit;
            HtmlButton uISubmitButton = this.UIHomePageNumericSequeWindow.UIHomePageNumericSequeDocument.UISubmitButton;
            #endregion

            // Type '98' in 'Number' text box
            uINumberEdit.Text = this.NumberEnteredParams.UINumberEditText;

            // Click 'Submit' button
            Mouse.Click(uISubmitButton, new Point(30, 17));
        }
        
        /// <summary>
        /// ListsCleared
        /// </summary>
        public void ListsCleared()
        {
            #region Variable Declarations
            HtmlHyperlink uIClearListsHyperlink = this.UIHomePageNumericSequeWindow.UIHomePageNumericSequeDocument.UIForm0Custom.UIClearListsHyperlink;
            #endregion

            // Click 'Clear Lists' link
            Mouse.Click(uIClearListsHyperlink, new Point(31, 14));
        }
        
        #region Properties
        public virtual NumberEnteredParams NumberEnteredParams
        {
            get
            {
                if ((this.mNumberEnteredParams == null))
                {
                    this.mNumberEnteredParams = new NumberEnteredParams();
                }
                return this.mNumberEnteredParams;
            }
        }
        
        public UIHomePageNumericSequeWindow UIHomePageNumericSequeWindow
        {
            get
            {
                if ((this.mUIHomePageNumericSequeWindow == null))
                {
                    this.mUIHomePageNumericSequeWindow = new UIHomePageNumericSequeWindow();
                }
                return this.mUIHomePageNumericSequeWindow;
            }
        }
        #endregion
        
        #region Fields
        private NumberEnteredParams mNumberEnteredParams;
        
        private UIHomePageNumericSequeWindow mUIHomePageNumericSequeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NumberEntered'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class NumberEnteredParams
    {
        
        #region Fields
        /// <summary>
        /// Type '98' in 'Number' text box
        /// </summary>
        public string UINumberEditText = "98";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHomePageNumericSequeWindow : BrowserWindow
    {
        
        public UIHomePageNumericSequeWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - Numeric Sequence Calculator";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageNumericSequeDocument UIHomePageNumericSequeDocument
        {
            get
            {
                if ((this.mUIHomePageNumericSequeDocument == null))
                {
                    this.mUIHomePageNumericSequeDocument = new UIHomePageNumericSequeDocument(this);
                }
                return this.mUIHomePageNumericSequeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageNumericSequeDocument mUIHomePageNumericSequeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHomePageNumericSequeDocument : HtmlDocument
    {
        
        public UIHomePageNumericSequeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Numeric Sequence Calculator";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:22657/";
            this.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINumberEdit
        {
            get
            {
                if ((this.mUINumberEdit == null))
                {
                    this.mUINumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Number";
                    this.mUINumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Number";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Number";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Number\" class=\"form-control\" id=\"N";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUINumberEdit.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
                    #endregion
                }
                return this.mUINumberEdit;
            }
        }
        
        public HtmlButton UISubmitButton
        {
            get
            {
                if ((this.mUISubmitButton == null))
                {
                    this.mUISubmitButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUISubmitButton.SearchProperties[HtmlButton.PropertyNames.Id] = "form-numeric-sequence-calculator-submit";
                    this.mUISubmitButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISubmitButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Submit";
                    this.mUISubmitButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISubmitButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISubmitButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn pull-left btn-default";
                    this.mUISubmitButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn pull-left btn-default\" id=\"fo";
                    this.mUISubmitButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISubmitButton.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
                    #endregion
                }
                return this.mUISubmitButton;
            }
        }
        
        public UIForm0Custom UIForm0Custom
        {
            get
            {
                if ((this.mUIForm0Custom == null))
                {
                    this.mUIForm0Custom = new UIForm0Custom(this);
                }
                return this.mUIForm0Custom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINumberEdit;
        
        private HtmlButton mUISubmitButton;
        
        private UIForm0Custom mUIForm0Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm0Custom : HtmlCustom
    {
        
        public UIForm0Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "form0";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "clearfix";
            this.FilterProperties["ControlDefinition"] = "class=\"clearfix\" id=\"form0\" role=\"form\" ";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIClearListsHyperlink
        {
            get
            {
                if ((this.mUIClearListsHyperlink == null))
                {
                    this.mUIClearListsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIClearListsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIClearListsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIClearListsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIClearListsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Clear Lists";
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:22657/";
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn pull-left btn-default";
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn pull-left btn-default\" href=\"";
                    this.mUIClearListsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIClearListsHyperlink.WindowTitles.Add("Home Page - Numeric Sequence Calculator");
                    #endregion
                }
                return this.mUIClearListsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIClearListsHyperlink;
        #endregion
    }
}
